// <auto-generated />
using System;
using JeopardyAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JeopardyAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231230170918_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JeopardyAPI.Models.Airdate", b =>
                {
                    b.Property<int>("Game")
                        .HasColumnType("int")
                        .HasColumnName("game");

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date")
                        .HasColumnName("airdate");

                    b.HasKey("Game");

                    b.ToTable("airdates", (string)null);
                });

            modelBuilder.Entity("JeopardyAPI.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("category");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CategoryName" }, "IX_categories_category")
                        .IsUnique()
                        .HasFilter("[category] IS NOT NULL");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("JeopardyAPI.Models.Classification", b =>
                {
                    b.Property<int?>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<int?>("ClueId")
                        .HasColumnType("int")
                        .HasColumnName("clue_id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ClueId");

                    b.ToTable("classifications", (string)null);
                });

            modelBuilder.Entity("JeopardyAPI.Models.Clue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int?>("Game")
                        .HasColumnType("int");

                    b.Property<int?>("Round")
                        .HasColumnType("int");

                    b.Property<int?>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Game");

                    b.ToTable("clues", (string)null);
                });

            modelBuilder.Entity("JeopardyAPI.Models.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Clue")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("documents", (string)null);
                });

            modelBuilder.Entity("JeopardyAPI.Models.Classification", b =>
                {
                    b.HasOne("JeopardyAPI.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("JeopardyAPI.Models.Clue", "Clue")
                        .WithMany()
                        .HasForeignKey("ClueId");

                    b.Navigation("Category");

                    b.Navigation("Clue");
                });

            modelBuilder.Entity("JeopardyAPI.Models.Clue", b =>
                {
                    b.HasOne("JeopardyAPI.Models.Airdate", "GameNavigation")
                        .WithMany("Clues")
                        .HasForeignKey("Game");

                    b.HasOne("JeopardyAPI.Models.Document", "IdNavigation")
                        .WithOne("ClueNavigation")
                        .HasForeignKey("JeopardyAPI.Models.Clue", "Id")
                        .IsRequired();

                    b.Navigation("GameNavigation");

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("JeopardyAPI.Models.Airdate", b =>
                {
                    b.Navigation("Clues");
                });

            modelBuilder.Entity("JeopardyAPI.Models.Document", b =>
                {
                    b.Navigation("ClueNavigation");
                });
#pragma warning restore 612, 618
        }
    }
}
